export const words = [
	['emel', ['e', 'mel']],
	['melek', ['me', 'lek']],
	['emin', ['e', 'min']],
	['nilan', ['ni', 'lan']],
	['nalan', ['na', 'lan']],
	['mola', ['mo', 'la']],
	['kama', ['ka', 'ma']],
	['koni', ['ko', 'ni']],
	['inme', ['in', 'me']],
	['anlam', ['an', 'lam']],
	['anla', ['an', 'la']],
	['anma', ['an', 'ma']],
	['elli', ['el', 'li']],
	['elek', ['e', 'lek']],
	['kola', ['ko', 'la']],
	['ilik', ['i', 'lik']],
	['ilikle', ['i', 'lik', 'le']],
	['leke', ['le', 'ke']],
	['lekeli', ['le', 'ke', 'li']],
	['ikili', ['i', 'ki', 'li']],
	['ekili', ['e', 'ki', 'li']],
];
