export const words = [
	['emel', ['e', 'mel']],
	['melek', ['me', 'lek']],
	['emin', ['e', 'min']],
	['nilan', ['ni', 'lan']],
	['nalan', ['na', 'lan']],
	['mola', ['mo', 'la']],
	['kama', ['ka', 'ma']],
	['koni', ['ko', 'ni']],
	['inme', ['in', 'me']],
	['anlam', ['an', 'lam']],
	['anla', ['an', 'la']],
	['anma', ['an', 'ma']],
	['elli', ['el', 'li']],
	['elek', ['e', 'lek']],
	['kola', ['ko', 'la']],
	['ilik', ['i', 'lik']],
	['ilikle', ['i', 'lik', 'le']],
	['leke', ['le', 'ke']],
	['lekeli', ['le', 'ke', 'li']],
	['ikili', ['i', 'ki', 'li']],
	['ekili', ['e', 'ki', 'li']],
	['melike', ['me', 'li', 'ke']],
	['kenan', ['ke', 'nan']],
	['kamil', ['ka', 'mil']],
	['kemal', ['ke', 'mal']],
	['kaan', ['ka', 'an']],
	['nail', ['na', 'il']],
	['leman',[`le`,`man`]],
	['kalem', ['ka', 'lem']],
	['kale', ['ka', 'le']],
	['okan', ['o', 'kan']],
	['olanak', ['o', 'la', 'nak']],
	['koloni', ['ko', 'lo', 'ni']],
	['kakao', ['ka', 'ka', 'o']],
	['koala', ['ko', 'a', 'la']],
	['ekol', ['e', 'kol']],
	['kaleli', ['ka', 'le', 'li']],
	['ilikle',[`i`,`lik`,`le`]],
	['kekik', ['ke', 'kik']],
	['inan', ['i', 'nan']],
	['kanal', ['ka', 'nal']],
	['nine', ['ni', 'ne']],
	['nane', ['na', 'ne']],
	['anneanne', ['an', 'ne', 'an', 'ne']],
	['nalana', ['na', 'la', 'na']],
	['ilkel', ['il', 'kel']],
	['ilke', ['il', 'ke']],
	['keklik', ['kek', 'lik']],
	['lale', ['la', 'le']],
	['aile', ['a','i', 'le']],
	['lila', ['li', 'la']],
	['ilk'],
	['alt'],
	['umut', ['u', 'mut']],
	['unlu', ['un', 'lu']],
	['unutma', ['u', 'nut', 'ma']],
	['unuttu', ['u', 'nut', 'tu']],
	['mumu', ['mu', 'mu']],
	['kokulu', ['ko', 'ku', 'lu']],
	['ellemem', ['el', 'le', 'mem']],
	['nemli', ['nem', 'li']],
	['kilim', ['ki', 'lim']],
	['iklim', ['ik', 'lim']],
	['kimin', ['ki', 'min']],
	['ninemin', ['ni', 'ne', 'min']],
	['mine', ['mi', 'ne']],
	[`emmi`,[`em`,`mi`]],
	[`alma`,[`al`,`ma`]],
	['elma', ['el', 'ma']],
	['ninene', ['ni', 'ne', 'ne']],
	['kokla', ['kok', 'la']],
	[`kukla`,[`ku`,`kla`]],
	['ekmek', ['ek', 'mek']],
	[`emine`,[`e`,`mi`,`ne`]],
	['kum'],
	['inelim', ['i', 'ne', 'lim']],
	[`lokum`,[`lo`,`kum`]],
	['minik', ['mi', 'nik']],
	['ona', ['o', 'na']],
	['onu', ['o', 'nu']],
	['konuk', ['ko', 'nuk']],
	['limonlu', ['li', 'mon', 'lu']],
	['atlet', ['at', 'let']],
	[`temel`,[`te`,`mel`]],
	['tatil', ['ta', 'til']],
	['mutlaka', ['mut', 'la', 'ka']],
	['anlat', ['an', 'lat']],
	[`ilet`,[`i`,`let`]],
	['tamam', ['ta', 'mam']],
	[`metin`,[`me`,`tin`]],
	[`tuttu`,[`tut`,`tu`]],
	['unutma', ['u', 'nut', 'ma']],
];
